  
name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 22,14 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
 

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 'Install dependencies'
      run: pip install -r requirements.txt
    - name: '开始运行'
      run: python index.py
   
    
    
    
    
    
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: python main.py
      
        
